[package]
name = "rbeext_serde_feature"
version = "0.1.0"
authors = ["Michael Yuan"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num-bigint = { version = "0.2", features = ["serde"] }
num = "0.2"
